### ISSUE TITLE
Coroutines show up as "Dead" when running

### ISSUE THREAD

**Issue by jonas-schievink** [chucklefish/rlua#30]
When a coroutine checks its own status, `ThreadStatus::Dead` is returned.

I'm not sure if this is intentional, `Active` would make a bit more sense, but that would mean that we can't know in advance whether calling `resume` will work. Maybe `Active` should be split into `Running` and `Ready`/`Resumable`/`Waiting` or something else?

Reproduction:
```rust
extern crate rlua;

use rlua::*;

fn main() {
    let lua = Lua::new();
    let f = lua.create_function(|lua, args| {
        let thrd: Thread = lua.unpack(args)?;
        println!("{:?}", thrd.status());
        lua.pack(())
    });
    let thrd = lua.create_thread(f);
    thrd.resume::<_, ()>(thrd.clone()).unwrap();
}
```

**Comment by kyren** [comment]
I'm not sure I have the ability to reliably test whether the calling Lua thread is the active one.  Look at the logic [here](https://github.com/chucklefish/rlua/blob/master/src/lua.rs#L885), a thread is in error if lua_status returns its error code, and it's yielded if it returns LUA_YEILD or it has the initial function on the top of the stack, as in, it hasn't had lua_resume called yet.  If neither of these is true, it's.. not resumable, and that's all the info I have.  I think the logic in the lua interpreter is that if the current thread is the same as the thread we're asking about, then obviously it's running, but I can't reliably get that information.

I could be EXTREMELY cheeky and check to see if the state pointer in the handle to the Thread is the same as the one for the actual thread, but that seems.. really quite wrong.  I think the solution is to name "Dead" something else, which I should do before releasing 0.9, which I kind of want to do ASAP.

Any suggestions?

**Comment by jonas-schievink** [comment]
It compares the state pointer, so that should be fine:

```c
  lua_State *co = getco(L);
  if (L == co) lua_pushliteral(L, "running");
```

**Comment by kyren** [comment]
>Hmm, coroutine.status manages to check this just fine. It returns "running" in this case.

Right, that's what I said, but not very clearly.  The interpreter definitely can get this information by comparing the current state pointer.  The problem is, it feels REALLY wrong for *me* to do that, because there is no.. running lua state REALLY.

> I could be EXTREMELY cheeky and check to see if the state pointer in the handle to the Thread is the same as the one for the actual thread, but that seems.. really quite wrong. 

I COULD absolutely check the "current" lua state pointer against the coroutine pointer, it's just.. what is the current one?  An obvious answer is the one stored in the LuaRef that is rlua::Thread, the problem is is that you could.. I guess get an Rc to the top level Lua or something, or have an Rc to the rlua::Thread, it just feels way too easy to break that logic.

**Comment by kyren** [comment]
I replied to this a minute ago, but I think github may have eaten my previous comment, very strange.  Anyway..

> Hmm, coroutine.status manages to check this just fine. It returns "running" in this case.

Yeah, definitely.  Like I said, the interpreter compares the coroutine pointer to the current thread pointer, and it can tell whether the thread is running.  The problem is, what is the current Lua thread from the perspective of rust?

So, I could check equality with the thread pointer in the rlua::Ref inside rlua::Thread, but that's wrong because you could get a different handle to the Thread that comes from some other copy of Lua somehow, using Rc say.  I COULD record the.. "last" thread that was executing somewhere in the registry, that would definitely be a way to solve it but it still feels wrong somehow, also it's a lot of work for information that is not actually that useful.

**Comment by jonas-schievink** [comment]
You're right, it really isn't that easy. That's a bit unfortunate, but probably renaming `Dead` is the best way... But I don't know what would be a better name.

**Comment by kyren** [comment]
I'll rename Active to Resumable, and Dead to.. I guess Unresumable, or something equally bad, I'll just explain it in the documentation.

**Comment by kyren** [comment]
I just named them Resumable / Unresumable, it's pretty poor naming, and kind of.. programmery. 
 820c38e806884ad560de2c4ae1a3c21d2ac0df13

**Comment by jonas-schievink** [comment]
I think the names are fine now. If someone find better ones we can always change them.
