### ISSUE TITLE
Soundness issue when borrowing Lua in a callback

### ISSUE THREAD

**Issue by kyren** [chucklefish/rlua#33]
Currently this compiles, and that is a problem because `lua` does not have a stable address.  Closures should go back to having a 'static lifetime.

```
    let lua = Lua::new();
    let globals = lua.globals();

    globals.set("boom", lua.create_function(|_, _| {
        lua.pack(lua.eval::<i32>("1 + 1", None)?)
    })).unwrap();
```

**Comment by jonas-schievink** [comment]
Just to clarify: This example in itself is still fine, the issue is that the borrow of `lua` isn't tracked by Rust, allowing code to move it while it's still borrowed: Doing `let moved = lua;` after the code above would compile (after a bit of restructuring) and lead to a dangling pointer deref when the function is called.

**Comment by kyren** [comment]
Thanks for the clarification, that is exactly right.  This is discussed further in #32 for anybody following along, but we should probably discuss it here more.

So, the proposed solution is simply to move callbacks back to 'static lifetime, and I don't see really any other way of solving this, but I think you might have some ideas?

**Comment by jonas-schievink** [comment]
Let's go back to `'static` for now. Should I feel *very* motivated I might search for a better solution, but I don't think that's happening anytime soon.
