### ISSUE TITLE
debug library not included

### ISSUE THREAD

**Issue by Timidger** [chucklefish/rlua#52]
Hey there,

The awesome lua library (which I'm trying to run with these bindings) makes great use of the `debug` functionality of Lua (specifically `debug.traceback`), but it's not included in these bindings. I could make it myself, but I just wanted to double check to see why it's not included.

**Comment by jonas-schievink** [comment]
This is done because some functions in there can cause unsafety (for example, `rlua` needs its own metatables on userdata and `debug` can change them, but there are deeper issues present even with the stock interpreter). But I agree that it can come in handy, so perhaps adding an `unsafe fn open_debug(&self)` to the `Lua` struct is a good idea.

**Comment by jonas-schievink** [comment]
The commit that removed the `debug` library is this one: 9c34d4b99f743c76435264b5e094ab1e9dee239a

**Comment by kyren** [comment]
I mentioned maybe just including the safe parts of debug by default, but I'm not 100% sure which parts are safe or not.  I assume `debug.traceback` is?

**Comment by Timidger** [comment]
Would you be against having an unsafe function that loads the entire debug library like @jonas-schievink  suggested? The awesome library basically uses the entire debug library, and so I'll need to enable it somehow.

Also side not: is there some thread/doc somewhere detailing what it is about debug that makes it unsound?

**Comment by kyren** [comment]
Probably there should be an API for selectively loading libraries instead of just default loading all of them minus default, and yeah have an unsafe function that loads debug as well.  However we do it should probably loudly mention that it is not suitable for sandboxing, but I could see it being useful in the case where you have a scripting interface that should not explicitly allow IO or something, but are comfortable with it not being resistant to actual attack.

**Comment by Timidger** [comment]
So is the only thing that's necessary is to some how expose the Lua pointer so I can pass it to [this function](https://docs.rs/rlua/0.9.6/rlua/ffi/fn.luaopen_debug.html)? Or do you want it done another way? I can submit a patch that adds this functionality, but I want you to tell me if there's a particular way to do it to make it seem the worst thing possible to do (e.g even more loud than those two unsafe functions)

**Comment by kyren** [comment]
No, I think I would just expose methods on the Lua struct that allowed you to manually open libs, and have separate Lua::new() into Lua::new() and maybe Lua::new_all_libs() or something, I haven't really thought about the names.  

I'm definitely trying to avoid handing out pointers to lua_State.  I don't really like the fact that the ffi module is even exported, I think I just accidentally left it exported in the original version, and it just sort of stayed that way on accident.  There's nothing you can do with it right now anyway, so I'd like to remove it.

At some theoretical future point I might be convinced to use a more complete external ffi bindings layer, and then I could see maybe having an unsafe method to get at the lua_State pointer, but until then doing it sort of opens the pandora's box of supporting the ffi layer I'm using right now.  I don't know if the situation has changed, but at the time there wasn't a Lua 5.3 ffi layer that supported building in visual studio, and also supported building both internally and externally, which is why I made my own.

If you need this soon, I can make some time to go ahead and do it, it shouldn't be hard.  If you'd like to try yourself, I was just going to add some nice API for choosing what libraries to load on startup or loading them after the fact, and the unsafe debug library would have to be loaded after the fact with an unsafe method.

**Comment by Timidger** [comment]
It's not urgent, and I'm sure you're busy working on that game :-). I'll take a crack at it and open a pr

**Comment by Timidger** [comment]
Huh, you weren't kidding about that unsafety. Loading the debug library causes a segfault somewhere deep in the callstack. I double checked and the debug library definitely looks like it was loaded correctly in my patch.

I'll just have to mock the debug library then. Too bad this couldn't fix my issue, wouldn't be surprised if the debug library was helpful to include now at this point. Thanks for helping out regardless :)

**Comment by kyren** [comment]
Wait, just loading the debug library causes this?  Maybe I need to look at that load_debug method closer, it definitely shouldn’t be unsafe to just load the debug library.  I can try and help you track down what’s going on if you want?

**Comment by Timidger** [comment]
No loading it doesn't cause it, when running the Awesome's default Lua it segfaults deep in a callstack somewhere while calling a debug function more than likely. I can call simple functions like e.g `debug.backtrace` fine but something else is causing the segfault.

If you want I can try to reproduce it with a basic minimal example, but that would take a little while and I'm guessing it's probably something to do with how debug works rather than any bug with rlua.

**Comment by Timidger** [comment]
Ok wait never mind this is weird...I found the offending line and maybe it is an issue with how it's loaded...

``lua
-- If LuaRocks is installed, make sure that packages installed through it are
-- found (e.g. lgi). If LuaRocks is not installed, do nothing.
pcall(require, "luarocks.loader")
```

That is the first line of the program, and commenting that out causes it to work

**Comment by kyren** [comment]
Hmm, I also see the setmetatable wrapper right there at the top, I wonder if that has something to do with it.  Maybe there’s a way of calling setmetatable that I’m not supporting correctly or haven’t wrapped it correctly?  I’ll look into that once I get home.

**Comment by Timidger** [comment]
For what it's worth, narrowed it down to [this line in luarocks loader](https://github.com/luarocks/luarocks/blob/master/src/luarocks/core/persist.lua#L72)

**Comment by Timidger** [comment]
Whoop, ok found the bug...

In [here](https://github.com/luarocks/luarocks/blob/master/src/luarocks/core/persist.lua#L72) you'll see it gets the old meta table, sets it to a new one, and then resets it once the work is done. However, if `getmetatable` returned `nil` then passing it to `setmetatable` fails in rlua **but not in the reference implementation**.

You should be able to pass nil to `setmetatable`.

Here is a small reproducible example. Load it however you want with rlua (I ran the repl and used `dofile`) and compare the results to the default lua interpreter.

```lua
print("setting up")
tbl = {hi = 5}
result = tbl or {}
globals = {}
globals_mt = {
  __index = function(t, k)
    globals[k] = true
  end
}
print("getting metatable")
local save_mt = getmetatable(result)
print("setting metatable")
setmetatable(result, globals_mt)
-- Do some work with the meta table set...
print("Resetting metatable")
setmetatable(result, save_mt)
print("done")

```

**Comment by mitchtbaum** [comment]
Related: #93
