### ISSUE TITLE
Difference to hlua [Readme]

### ISSUE THREAD

**Issue by ShalokShalom** [chucklefish/rlua#64]
You write: 

>  This crate has the following differences with hlua:
>     Handles to Lua values use the Lua registry, not the stack
>     Handles to Lua values are all internally mutable
>     Handles to Lua values have non-mutable borrows to the main Lua object, so there can be multiple handles or long lived handles
>     Targets Lua 5.3

What is what?
What is hlua and which one your project?

**Comment by Timidger** [comment]
It may seem unclear, but all of those points are what rlua does. Hlua does the "opposite" (eg it utilizes the Lua stack instead of sticking everything into the registry).

The README seems to assume knowledge of hlua which not everybody has (but did when this was first released since that was the main crate used to interface Rust and Lua)

**Comment by kyren** [comment]
I clarified it a little bit, and removed the suggestion to use hlua over rlua (though, it was a fairly weak suggestion to begin with).
