### ISSUE TITLE
`RegistryKey` implements no traits and is not exported

### ISSUE THREAD

**Issue by jonas-schievink** [chucklefish/rlua#65]
This makes the raw registry API ~~rather useless~~ very hard to use since you can't name the type. The string-based one still works fine, of course.

**Comment by kyren** [comment]
it's not supposed to implement Copy and Clone, as that would make it possible to invalidate keys and make keys point to random values.  It could maybe implement Debug?

Not being exposed however was just an embarrassing oversight.

If I just make it properly public would that make it useful enough to keep around, or without Copy + Clone do you think it would be really difficult to use?

**Comment by jonas-schievink** [comment]
Ah, now I understand how that API works! Sure, then `Copy + Clone` isn't needed. But couldn't you use a `RegistryKey` from one `Lua` with the methods of another?

**Comment by jonas-schievink** [comment]
We *might* be able to use the same approach that the [indexing](https://docs.rs/indexing/0.3.2/indexing/) crate uses to make this sound, but I'm not sure if that's worth the hassle, given that the string-based API works fine.

**Comment by kyren** [comment]
Yeah, you could absolutely use a RegistryKey with the wrong instance of Lua.  I think that I decided that it wasn't unsafe to allow that, but now I think I was wrong.  It's wrong because you can trigger a delete of any random registry value, and that is definitely unsafe to do.

There's actually a pretty easy fix, give each RegistryKey an Rc to () which is shared by Lua, then always assert that they are ptr_eq when being used.  There's already a similar assert for LuaRef types, but we can't use pointers because Lua could be dropped and added with a new replacement Lua at the same address.  Using Rc fixes this, though.

**Comment by kyren** [comment]
Okay, I think this API is now properly exposed, and the safety hole is plugged, and there are tests for both cross Lua LuaRefs and cross Lua RegistryKeys

**Comment by jonas-schievink** [comment]
Had a quick look, that's a really neat solution! Closing.

**Comment by kyren** [comment]
it's not the 100% best solution since it's at runtime rather than compile time.  I'm assuming that the thing the indexing crate does is at compile time?  Maybe I'll look into how they achieve that and look at implementing that in the future, at least for ref types.

**Comment by jonas-schievink** [comment]
Yeah, I haven't looked too deeply into how it works, but it's definitely at compile time. rlua's approach isn't too bad either since it's just a small predictable branch and doesn't incur overhead if it's unused.
