### ISSUE TITLE
Serde Serializer/Deserializer for Lua Value

### ISSUE THREAD

**Issue by zrkn** [chucklefish/rlua#67]
Currently conversion of Rust types to Lua `Value`s is uses `FromLua` and `ToLua` traits. However, it might be cumbersome to implement these traits manually. One solution is to implement derive procedural macro. However, it is quite a lot of work and introduces extra dependency for end user.

On the other hand, a very similar data type is used in `serde_json` - [Value](https://docs.rs/serde_json/1.0.9/serde_json/enum.Value.html). With `Serializer`/`Deserializer` traits implemented, basically any data type with `Serialize`/`Deserialize` trait can be converted to/from it.

I have test implementation of `Serializer` in [zrkn/rlua](https://github.com/zrkn/rlua/tree/serde) (mostly copied from `serde_json`). In my project I only need to convert Rust values to Lua, so it works for me. However if you would consider merging this feature upstream I can implement `Deserializer` too and make pull request.

**Comment by kyren** [comment]
I've definitely had the same idea, it's cool that you implemented this and I'll definitely take a look at it.

The problem with doing this though, is that it creates two paths for serialization, the Serialize / Deserialize path and the ToLua / FromLua path.

If there a way that we could provide some sort of `to_lua_serialize!` and `from_lua_deserialize` macros that make a struct that is Serialize / Deserialize implement ToLua / FromLua, that would be really interesting.  I haven't looked into it, but I don't think that's possible to do in a way where it forwards to ToLua / FromLua on the fields of the struct implementing Serialize / Deserialize, and if you have two separate serialization systems, I don't think that's going to work out very well.

The problem is something like this, suppose you have a `struct Complicated` with a bespoke `impl ToLua for Complicated` and `impl FromLua for Complicated`.  Then, if you have a `#[derive(Serialize, Deserialize)] struct Compound { complicated: Complicated }`, at best using Serialize / Deserialize to do the Lua conversion won't compile, but at worst it may actually use a serialization that you don't actually want.  I don't really want there to be multiple parallel ways to do Lua serialization.

**Comment by zrkn** [comment]
There is a difference between `ToLua`/`FromLua` conversion path and `Serialize`/`Deserialize`, which can be a reason to keep them separate. `ToLua`/`FromLua` consumes `self`, when `Serialize`/`Deserialize` takes it by reference. Basically, first is _conversion_ and second is _serialization_ which is a bit different operations. End user can choose which is more appropriate for them.

**Comment by zrkn** [comment]
Agreed. Implemented in separate crate - https://github.com/zrkn/rlua_serde/
Thanks for feedback, I think we can close this.
